meetings:
    type:     rest
    resource: AppBundle\ApiController\MeetingController
    name_prefix: api_

minutes:
    type:     rest
    parent:   meetings
    resource: AppBundle\ApiController\MinutesController
    name_prefix: api_
